name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Pull latest code from remote server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} "cd ${{ vars.REPO_PATH }} && git pull origin main"

    - name: Run deployment script on remote server
      run: |
        # echo "${{ secrets.SSH_KEY }}" > key.pem
        # chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} "cd ${{ vars.REPO_PATH }} && ./${{ vars.REMOTE_SCRIPT }}"
    