name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Push code to remote server
      run: |
        git remote add remote_server ssh://${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}:${{vars.REPO_PATH}}
        git fetch remote_server main
        git merge remote_server/main --no-edit
        git push remote_server main
      env:
        GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'

    # - name: Run deployment script on remote server
    #   run: |
    #     echo "${{ secrets.SSH_KEY }}" > key.pem
    #     chmod 600 key.pem
    #     ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'bash -s' < ${{ secrets.REMOTE_SCRIPT }}
